### PR TITLE
Fixing magento1.7 changing the way of accessing the order from checkout session

### LINKED ISSUE #946: getLastRealOrder() doesn't exist
### Preconditions

1. Magento 1.7.0.2
2. mc-magento v1.1.15.2

### Steps to reproduce

1. On successful checkout this [template file](https://github.com/mailchimp/mc-magento/blob/develop/app/design/frontend/base/default/template/ebizmarts/mailchimp/checkout/success/groups.phtml) is rendered. The third line attempts for `$block->getInterest();` which has a call to ` $this->getSessionLastRealOrder();`.
2. `getSessionLastRealOrder()` is defined this way:

```
protected function getSessionLastRealOrder()
{
    return Mage::getSingleton('checkout/session')->getLastRealOrder();
}
```
but `getLastRealOrder()` on `Mage_Checkout_Model_Session` is neither a normal method nor an attribute code to magically be set or gotten (however it seems to exist in Magento 2.0) the reason it evaluates to null.

### Expected result

1. `groups.phtml` to render sucessfully.

### Actual result

1. `Fatal error: Call to a member function getCustomerEmail() on null in /*/app/code/community/Ebizmarts/MailChimp/Block/Checkout/Success/Groups.php on line 42`

### PR DESCRIPTION
**Pull request by roberto-ebizmarts**
closes #946

### CODE REVIEW

File: app/code/community/Ebizmarts/MailChimp/Helper/Data.php [hunk 1]
```diff
@@ -4290,4 +4290,34 @@ public function getApiKeyValue()
...
     }
+
+    /**
+     * @return Mage_Sales_Model_Order
+     */
+    public function getSessionLastRealOrder()
+    {
+        $checkoutSession = $this->getCheckOutSession();
+        $order = $checkoutSession->getLastRealOrder();
+        if(is_null($order)){
```
Comment (centerax) [inline app/code/community/Ebizmarts/MailChimp/Helper/Data.php]: change `if(is_null($order)){` to `if (is_null($order)) {` for better readability

File: app/code/community/Ebizmarts/MailChimp/Helper/Data.php [hunk 2]
```diff
@@ -4290,4 +4290,35 @@ public function getApiKeyValue()
...
     }
+
+    /**
+     * @return Mage_Sales_Model_Order
+     */
+    public function getSessionLastRealOrder()
+    {
+        $checkoutSession = $this->getCheckOutSession();
+        $order = $checkoutSession->getLastRealOrder();
+        if (is_null($order))
```
Comment (centerax) [inline app/code/community/Ebizmarts/MailChimp/Helper/Data.php]: https://travis-ci.org/mailchimp/mc-magento/jobs/545896783#L4426

Comment (centerax) [inline app/code/community/Ebizmarts/MailChimp/Helper/Data.php]: https://travis-ci.org/mailchimp/mc-magento/jobs/545896783#L4428

File: app/code/community/Ebizmarts/MailChimp/Helper/Data.php [hunk 3]
```diff
@@ -4290,4 +4290,35 @@ public function getApiKeyValue()
...
+        {
+            $orderId = $checkoutSession->getLastOrderId();
+            $order = $this->getSalesOrderModel()->load($orderId);
+        }
```
Comment (centerax) [inline app/code/community/Ebizmarts/MailChimp/Helper/Data.php]: https://travis-ci.org/mailchimp/mc-magento/jobs/545896783#L4430
