### PR TITLE
Issue895

### LINKED ISSUE #895: Process webhook error 'You must provide a MailChimp API key'
### Preconditions
1. Magento 1 any version
2. Mailchimp for Magento 1.1.15

### Steps to reproduce
1. Create two storeviews using different API keys
2. Leave empty API key field for default scope
3. Update subscriber information in mailchimp for one subscriber that not exists in magento database.

### Expected result
New subscriber successfully created if not exists in magento database.

### Actual result

exception 'Ebizmarts_MailChimp_Helper_Data_ApiKeyException' with message 'You must provide a MailChimp API key' in /chroot/home/xxxxxxxxx/html/app/code/community/Ebizmarts/MailChimp/Helper/Data.php:1089
Stack trace:
#0 /chroot/home/xxxxxxxxx/html/app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php(241): Ebizmarts_MailChimp_Helper_Data->getApi(0)
#1 /chroot/home/xxxxxxxxx/html/app/code/community/Ebizmarts/MailChimp/Model/ProcessWebhook.php(71): Ebizmarts_MailChimp_Model_ProcessWebhook->_profile(Array)
#2 /chroot/home/xxxxxxxxx/html/app/code/community/Ebizmarts/MailChimp/Model/Cron.php(41): Ebizmarts_MailChimp_Model_ProcessWebhook->processWebhookData()
#3 [internal function]: Ebizmarts_MailChimp_Model_Cron->processWebhookData(Object(Aoe_Scheduler_Model_Schedule))
#4 /chroot/home/xxxxxxxxx/html/app/code/community/Aoe/Scheduler/Model/Schedule.php(217): call_user_func_array(Array, Array)
#5 /chroot/home/xxxxxxxxx/html/app/code/community/Aoe/Scheduler/Model/Schedule.php(623): Aoe_Scheduler_Model_Schedule->runNow(true)
#6 /chroot/home/xxxxxxxxx/html/app/code/community/Aoe/Scheduler/Model/Observer.php(39): Aoe_Scheduler_Model_Schedule->process()
#7 /chroot/home/xxxxxxxxx/html/app/code/core/Mage/Core/Model/App.php(1358): Aoe_Scheduler_Model_Observer->dispatch(Object(Varien_Event_Observer))
#8 /chroot/home/xxxxxxxxx/html/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Aoe_Scheduler_Model_Observer), 'dispatch', Object(Varien_Event_Observer))
#9 /chroot/home/xxxxxxxxx/html/app/Mage.php(454): Mage_Core_Model_App->dispatchEvent('default', Array)
#10 /chroot/home/xxxxxxxxx/html/shell/scheduler.php(519): Mage::dispatchEvent('default', Array)
#11 /chroot/home/xxxxxxxxx/html/shell/scheduler.php(37): Aoe_Scheduler_Shell_Scheduler->cronAction()
#12 /chroot/home/xxxxxxxxx/html/shell/scheduler.php(545): Aoe_Scheduler_Shell_Scheduler->run()
#13 {main}

### PR DESCRIPTION
**Pull request by brian-ebizmarts**
closes #895

### CODE REVIEW

File: dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/ProcessWebhookTest.php [hunk 1]
```diff
@@ -0,0 +1,247 @@
...
+        $subscriberMock->expects($this->once())->method('setSubscriberFirstname')->with($fname)->willReturn($subscriberMock);
+        $subscriberMock->expects($this->once())->method('setSubscriberLastname')->with($lname)->willReturn($subscriberMock);
+        $subscriberMock->expects($this->once())->method('setSubscriberSource')->with($subscribeSource)->willReturn($subscriberMock);
+        $subscriberMock->expects($this->once())->method('save')->willReturn($subscriberMock);
+
+        $processWebhookMock->_profile($data);
+    }
+
+
+    public function testWwebhookProfileSubscriberNotExistsMemberSubscribed(){
```
Comment (Santiagoebizmarts) [inline dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/ProcessWebhookTest.php]: Remove extra w in function name.

File: dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/ProcessWebhookTest.php [hunk 2]
```diff
@@ -0,0 +1,247 @@
...
+
+        $helperMock->expects($this->once())->method('subscribeMember')
+            ->with($subscriberMock)
+            ->willReturn(null);
+
+        //$subscriberMock->expects($this->once())->method('getStoreId')->willReturn($subscriberMock);
+        $processWebhookMock->_profile($data);
+    }
+
+    public function testWwebhookProfileSubscriberNotExistsMemberUnsubscribed(){
```
Comment (Santiagoebizmarts) [inline dev/tests/mailchimp/tests/app/Ebizmarts/MailChimp/Model/ProcessWebhookTest.php]: Remove extra w from function name.
