### PR TITLE
Get guest information from orders made with the same email address

### LINKED ISSUE #545: Get guest information from orders made with the same email address
### Preconditions
1. Mailchimp for Magento 1.1.15.
2. Magento any version.

### Steps to reproduce
1. Place an order with a new user that is not a registered user and is not subscribed to the list
2. Subscribe that email to the list.

### Expected result
1. The data of the order will be used for the merge fields to send to Mailchimp.

### Actual result
1. The subscriber will be synced to Mailchimp without any data in the merge fields.

### LINKED ISSUE #937: Add default merge var for province/state
### Steps to reproduce
If you want to make a campaign segmented by a province/state, you can't do it properly because the MailChimp extension doesn't send a province merge field.

### Expected result
province/state is sent by default

### Actual result
province/state is sent in the address merge field but not separately

### PR DESCRIPTION
**Pull request by luciaebizmarts**
- get guest information from order if exist for a new subscriber 
- implemented the function getLastOrderByEmail adapted the function getLastDateOfPurchase 
- implemented test for getLastOrderByEmail and adapted test for getLastDateOfPurchase
- closes #545
- closes #937

### CODE REVIEW

File: app/code/community/Ebizmarts/MailChimp/Helper/Data.php [hunk 1]
```diff
@@ -1688,13 +1688,14 @@ protected function getCoreWebsite()
      * @param  $subscriberEmail
      * @return null
      */
-    public function getLastDateOfPurchase($subscriberEmail)
+    public function getLastDateOfPurchase($subscriberEmail, $lastOrder = null)
     {
         $lastDateOfPurchase = null;
+        if (!$lastOrder) {
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Helper/Data.php]: Use exact operator $lastOrder === null to avoid false positives in case 0 or '' is given.

File: app/code/community/Ebizmarts/MailChimp/Helper/Data.php [hunk 2]
```diff
@@ -1688,13 +1688,14 @@ protected function getCoreWebsite()
...
+           $lastOrder = $this->getLastOrderByEmail($subscriberEmail);
+        }
 
-        $orderCollection = $this->getOrderCollectionByCustomerEmail($subscriberEmail);
-        if ($orderCollection->getSize()) {
-            $lastOrder = $orderCollection->setOrder('created_at', 'DESC')->getFirstItem();
+        if ($lastOrder) {
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Helper/Data.php]: Use exact operator $lastOrder !== null

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 3]
```diff
@@ -150,18 +148,20 @@ protected function _getInterest($subscriber)
...
+        $maps = $this->unserilizeMapFields($mapFields);
+        $websiteId = $this->getWebSiteByStoreId($storeId);
+        $attrSetId = $this->getEntityAttributeCollection()
             ->setEntityTypeFilter(1)
             ->addSetInfo()
             ->getData();
         $mergeVars = array();
         $subscriberEmail = $subscriber->getSubscriberEmail();
-        $customer = Mage::getModel('customer/customer')->setWebsiteId($websiteId)->load($subscriber->getCustomerId());
+        $customer = $this->getCustomerModel()->setWebsiteId($websiteId)->load($subscriber->getCustomerId());
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: Extract to function getCustomerByWebsiteAndId

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 4]
```diff
@@ -578,6 +422,311 @@ protected function addError($errorMessage)
...
+                $dop = $helper->getLastDateOfPurchase($subscriberEmail, $lastOrder);
+                if ($dop) {
+                    $mergeVars[$key] = $dop;
+                }
+                break;
+            case 'store_code':
+                $storeCode = Mage::getModel('core/store')->load($storeId)->getCode();
+                $mergeVars[$key] = $storeCode;
+        }
+        Mage::log($mergeVars[$key], null, 'testing.log', true);
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: Remove log entry.

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 5]
```diff
@@ -578,6 +422,311 @@ protected function addError($errorMessage)
...
+    {
+        switch ($attributeCode) {
+            case 'email':
+                break;
+            case 'default_billing':
+            case 'default_shipping':
+                $address = $customer->getPrimaryAddress($attributeCode);
+                $addressData = $this->getAddressData($address);
+
+                $addressData = $this->getAddressFromLastOrder($lastOrder, $addressData);
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: Avoid rewriting variable, maybe extract to getAddressData.

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 6]
```diff
@@ -578,6 +422,311 @@ protected function addError($errorMessage)
...
+
+                if (count($addressData)) {
+                    $mergeVars[$key] = $addressData;
+                }
+                break;
+            case 'gender':
+                if ($customer->getData($attributeCode)) {
+                    $genderValue = $customer->getData($attributeCode);
+                    if ($genderValue == 1) {
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: Extract if condition to function and use constant for number.

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 7]
```diff
@@ -578,6 +422,311 @@ protected function addError($errorMessage)
...
+                        $mergeVars[$key] = 'Male';
+                    } elseif ($genderValue == 2) {
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: Extract if condition to function and use constant for number.

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 8]
```diff
@@ -578,6 +422,311 @@ protected function addError($errorMessage)
...
+                        $mergeVars[$key] = 'Female';
+                    }
+                }
+                break;
+            case 'group_id':
+                if ($customer->getData($attributeCode)) {
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: Extract to function getCustomerGroupLabel to adapt to the same format as other cases

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 9]
```diff
@@ -578,6 +422,311 @@ protected function addError($errorMessage)
...
+                    $group_id = (int)$customer->getData($attributeCode);
+                    $customerGroup = Mage::helper('customer')->getGroups()->toOptionHash();
+                    $mergeVars[$key] = $customerGroup[$group_id];
+                } else {
+                    $mergeVars[$key] = 'NOT LOGGED IN';
+                }
+                break;
+            case 'firstname':
+                $firstName = $customer->getFirstname();
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: Extract to function getFirstName to adapt to the same format as other cases

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 10]
```diff
@@ -578,6 +422,311 @@ protected function addError($errorMessage)
...
+                        $firstName = $lastOrder->getCustomerFirstname();
+                    }
+                }
+
+                if ($firstName) {
+                    $mergeVars[$key] = $firstName;
+                }
+                break;
+            case 'lastname':
+                $lastName = $customer->getLastname();
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: Extract to function getLastName to adapt to the same format as other cases

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 11]
```diff
@@ -578,6 +422,311 @@ protected function addError($errorMessage)
...
+                $addressData = $this->getAddressData($address);
+
+                $addressData = $this->getAddressFromLastOrder($lastOrder, $addressData);
+
+                if (count($addressData)) {
+                    $mergeVars[$key] = $addressData;
+                }
+                break;
+            case 'gender':
+                if ($customer->getData($attributeCode)) {
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: Extract to function getCustomerGroupLabel to adapt to the same format as other cases

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 12]
```diff
@@ -578,6 +422,311 @@ protected function addError($errorMessage)
...
+                $websiteId = $this->getWebSiteByStoreId($storeId);
+                $mergeVars[$key] = $websiteId;
+                break;
+            case 'created_in':
+                $storeName = Mage::getModel('core/store')->load($storeId)->getName();
+                $mergeVars[$key] = $storeName;
+                break;
+            case 'dob':
+                if ($customer->getData($attributeCode)) {
+                    $mergeVars[$key] = date("m/d", strtotime($customer->getData($attributeCode)));
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: Extract to function for clearer reading.

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 13]
```diff
@@ -578,6 +422,311 @@ protected function addError($errorMessage)
...
+                }
+                break;
+            default:
+                $attrValue = $customer->getData($attributeCode);
+                if ($attribute['frontend_input'] == 'select' && $attrValue) {
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: Extract to function getUnknownMergeField for clearer reading.

File: app/code/community/Ebizmarts/MailChimp/Helper/Data.php [hunk 14]
```diff
@@ -4124,6 +4125,21 @@ protected function getModelMailchimpEcommerceSyncData()
...
+     /**
+     * @param $email
+     * @return array | return the latest order made by the email passed by parameter if exists.
+     *
+     */
+    public function getLastOrderByEmail($email)
+    {
+        $orderCollection = $this->getOrderCollectionByCustomerEmail($email);
+        $lastOrder = array();
+        if ($orderCollection->getSize()) {
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Helper/Data.php]: use > 0 for clearer reading and extract to new function.

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 15]
```diff
@@ -20,15 +22,13 @@ class Ebizmarts_MailChimp_Model_Api_Subscribers
...
     }
 
     public function createBatchJson($listId, $storeId, $limit)
     {
-        /**
-         * Ebizmarts_MailChimp_Helper_Data
-         */
-        $helper = $this->mcHelper;
+        $helper = $this->getMailchimpHelper();
         $thisScopeHasSubMinSyncDateFlag = $helper->getIfConfigExistsForScope(Ebizmarts_MailChimp_Model_Config::GENERAL_SUBMINSYNCDATEFLAG, $storeId);
```
Comment (centerax) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: https://travis-ci.org/mailchimp/mc-magento/jobs/545910306#L3161

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 16]
```diff
@@ -20,15 +22,13 @@ class Ebizmarts_MailChimp_Model_Api_Subscribers
...
         $thisScopeHasList = $helper->getIfConfigExistsForScope(Ebizmarts_MailChimp_Model_Config::GENERAL_LIST, $storeId);
```
Comment (centerax) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: https://travis-ci.org/mailchimp/mc-magento/jobs/545910306#L3163

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 17]
```diff
@@ -173,166 +175,18 @@ public function getMergeVars($subscriber)
...
 
-                            Mage::dispatchEvent(
-                                'mailchimp_merge_field_send_before', array(
-                                    'customer_id' => $customer->getId(),
-                                    'subscriber_email' => $subscriberEmail,
-                                    'merge_field_tag' => $attributeCode,
-                                    'merge_field_value' => &$eventValue
-                                )
-                            );
+                            $mergeVars = $this->customerAttributes($subscriber, $attributeCode, $customer, $mergeVars, $key, $storeId, $attribute);
```
Comment (centerax) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: https://travis-ci.org/mailchimp/mc-magento/jobs/545910306#L3192

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 18]
```diff
@@ -173,166 +175,18 @@ public function getMergeVars($subscriber)
...
-                        case 'dop':
-                            $dop = $helper->getLastDateOfPurchase($subscriberEmail);
-                            if ($dop) {
-                                $eventValue = $mergeVars[$key] = $dop;
-                            }
-                            break;
-                        case 'store_code':
-                            $storeCode = Mage::getModel('core/store')->load($storeId)->getCode();
-                            $eventValue = $mergeVars[$key] = $storeCode;
+                    $mergeVars = $this->customizedAttributes($customAtt, $customer, $mergeVars, $key, $helper, $subscriberEmail, $storeId);
```
Comment (centerax) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: https://travis-ci.org/mailchimp/mc-magento/jobs/545910306#L3194

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 19]
```diff
@@ -173,166 +175,18 @@ public function getMergeVars($subscriber)
...
+                    if (isset($mergeVars[$key])) {
+                        $eventValue = $mergeVars[$key];
                     }
```
Comment (centerax) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: https://travis-ci.org/mailchimp/mc-magento/jobs/545910306#L3196

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 20]
```diff
@@ -578,6 +428,288 @@ protected function addError($errorMessage)
...
+     * @param $customAtt
+     * @param $customer
+     * @param $mergeVars
+     * @param $key
+     * @param $helper
+     * @param $subscriberEmail
+     * @param $storeId
+     * @return array
+     */
+    protected function customizedAttributes($customAtt, $customer, $mergeVars, $key, $helper, $subscriberEmail, $storeId)
```
Comment (centerax) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: https://travis-ci.org/mailchimp/mc-magento/jobs/545910306#L3236

441 | WARNING | [ ] Function's cyclomatic complexity (24) exceeds
     |         |     allowed maximum of 20
 441 | WARNING | [ ] The method parameter $helper is never used
 441 | WARNING | [ ] Line exceeds 120 characters; contains 121

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 21]
```diff
@@ -578,6 +428,288 @@ protected function addError($errorMessage)
...
+     * @param $subscriber
+     * @param $attributeCode
+     * @param $customer
+     * @param $mergeVars
+     * @param $key
+     * @param $storeId
+     * @param $attribute
+     * @return array | returns an array of mergeFields.
+     */
+    protected function customerAttributes($subscriber, $attributeCode, $customer, $mergeVars, $key, $storeId, $attribute)
```
Comment (centerax) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: 524 | WARNING | [ ] Function's cyclomatic complexity (20) exceeds
     |         |     10; consider refactoring the function
 524 | WARNING | [ ] Line exceeds 120 characters; contains 121
     |         |     characters
 534 | WARNING | [ ] count(...) function should not be used to check
     |         |     if array is empty. Use empty(...) language
     |         |     construct instead
 546 | WARNING | [ ] Variable "group_id" is not in valid camel caps
     |         |     format
 548 | WARNING | [ ] Variable "group_id" is not in valid camel caps
     |         |     format
 587 | WARNING | [x] No blank line found after control structure
 588 | WARNING | [ ] Line exceeds 120 characters; contains 122
     |         |     characters
 588 | WARNING | [ ] This comment is 70% valid code; is this
     |         |     commented out code?

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 22]
```diff
@@ -578,6 +428,288 @@ protected function addError($errorMessage)
...
+    /**
+     * @param $lastOrder
+     * @return array | return an array with the address from the order if exist and the addressData is empty.
+     */
+    protected function getAddressFromLastOrder($lastOrder)
+    {
+        $addressData = array();
+        if ($lastOrder && $lastOrder->getShippingAddress()) {
+            $addressData = $lastOrder->getShippingAddress();
+        }
```
Comment (centerax) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: https://travis-ci.org/mailchimp/mc-magento/jobs/545910306#L3258

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 23]
```diff
@@ -598,4 +730,174 @@ protected function getSubscriberSyncDataItem($itemId, $magentoStoreId)
...
+        $lastOrder = $this->getSubscriberLastOrder();
+        $firstName = $customer->getFirstname();
+
+        if (!$firstName) {
+            if ($subscriber->getSubscriberFirstname()) {
+                $firstName = $subscriber->getSubscriberFirstname();
+            } elseif ($lastOrder && $lastOrder->getCustomerFirstname()) {
+                $firstName = $lastOrder->getCustomerFirstname();
+            }
+        }
```
Comment (centerax) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: https://travis-ci.org/mailchimp/mc-magento/jobs/545910306#L3261

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 24]
```diff
@@ -598,4 +730,174 @@ protected function getSubscriberSyncDataItem($itemId, $magentoStoreId)
...
+        $lastOrder = $this->getSubscriberLastOrder();
+        $lastName = $customer->getLastname();
+
+        if (!$lastName) {
+            if ($subscriber->getSubscriberLastname()) {
+                $lastName = $subscriber->getSubscriberLastname();
+            } elseif ($lastOrder && $lastOrder->getCustomerLastname()) {
+                $lastName = $lastOrder->getCustomerLastname();
+            }
+        }
```
Comment (centerax) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: https://travis-ci.org/mailchimp/mc-magento/jobs/545910306#L3262

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 25]
```diff
@@ -598,4 +730,174 @@ protected function getSubscriberSyncDataItem($itemId, $magentoStoreId)
...
+     * @param $key
+     * @param $attribute
+     * @return mixed
+     */
+    protected function getUnknownMergeField($attributeCode, $customer, $attribute)
+    {
+        $optionValue = null;
+
+        $attrValue = $this->getCustomerGroupLabel($attributeCode, $customer);
+        if($attrValue!== null) {
```
Comment (centerax) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: https://travis-ci.org/mailchimp/mc-magento/jobs/545910306#L3263

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 26]
```diff
@@ -598,4 +730,174 @@ protected function getSubscriberSyncDataItem($itemId, $magentoStoreId)
...
+    }
+
+    /**
+     * @param $attributeCode
+     * @param $customer
+     * @return string | returns the date of birth of the customer string format.
+     */
+    protected function getDateOfBirth($attributeCode, $customer)
+    {
+        return date("m/d", strtotime($this->getCustomerGroupLabel($attributeCode, $customer)));
```
Comment (centerax) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: https://travis-ci.org/mailchimp/mc-magento/jobs/545910306#L3264

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 27]
```diff
@@ -598,4 +730,174 @@ protected function getSubscriberSyncDataItem($itemId, $magentoStoreId)
...
+     * @param $subscriberEmail
+     * @return mixed
+     * @throws Mage_Core_Exception
+     */
+    protected function saveLastOrderInSession($subscriberEmail)
+    {
+        $lastOrder = $this->getLastOrderByEmail($subscriberEmail);
+        if ($this->getSubscriberLastOrder()) {
+            Mage::unregister('subscriber_last_order');
+        }
```
Comment (centerax) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: https://travis-ci.org/mailchimp/mc-magento/jobs/545910306#L3266

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 28]
```diff
@@ -598,4 +730,174 @@ protected function getSubscriberSyncDataItem($itemId, $magentoStoreId)
...
+     * @param  $subscriberEmail
+     * @return null
+     */
+    public function getLastDateOfPurchase($subscriberEmail)
+    {
+        $lastOrder = $this->getSubscriberLastOrder();
+        $lastDateOfPurchase = null;
+        if ($lastOrder === null) {
+            $lastOrder = $this->getLastOrderByEmail($subscriberEmail);
+        }
```
Comment (centerax) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: https://travis-ci.org/mailchimp/mc-magento/jobs/545910306#L3267

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 29]
```diff
@@ -598,4 +730,174 @@ protected function getSubscriberSyncDataItem($itemId, $magentoStoreId)
...
+        if ($lastOrder !== null) {
+            $lastDateOfPurchase = $lastOrder->getCreatedAt();
+        }
```
Comment (centerax) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: https://travis-ci.org/mailchimp/mc-magento/jobs/545910306#L3268

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 30]
```diff
@@ -598,4 +730,174 @@ protected function getSubscriberSyncDataItem($itemId, $magentoStoreId)
...
+        return $lastDateOfPurchase;
+    }
+
+    /**
+     * @param $email
+     * @return Mage_Sales_Model_Resource_Order_Collection | return the latest order made by the email passed by parameter if exists.
```
Comment (centerax) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: https://travis-ci.org/mailchimp/mc-magento/jobs/545910306#L3269

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 31]
```diff
@@ -598,4 +730,174 @@ protected function getSubscriberSyncDataItem($itemId, $magentoStoreId)
...
+     *
+     */
+    public function getLastOrderByEmail($email)
+    {
+        $helper = $this->getMailchimpHelper();
+        $orderCollection = $helper->getOrderCollectionByCustomerEmail($email);
+        $lastOrder = null;
+        if ($this->isNotEmptyOrderCollection($orderCollection)) {
+            $lastOrder = $orderCollection->setOrder('created_at', 'DESC')->getFirstItem();
```
Comment (centerax) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: https://travis-ci.org/mailchimp/mc-magento/jobs/545910306#L3271

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 32]
```diff
@@ -598,4 +730,174 @@ protected function getSubscriberSyncDataItem($itemId, $magentoStoreId)
...
+        }
```
Comment (centerax) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: https://travis-ci.org/mailchimp/mc-magento/jobs/545910306#L3273

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 33]
```diff
@@ -366,9 +184,10 @@ public function getMergeVars($subscriber)
      */
     public function updateSubscriber($subscriber, $updateStatus = false)
     {
+        Mage::log(__METHOD__, null, 'events.log', true);
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: Remove log entry

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 34]
```diff
@@ -105,20 +124,31 @@ public function createBatchJson($listId, $storeId, $limit)
...
+
+        $mailChimpTags = Mage::getModel('mailchimp/api_subscribers_mailchimpTags');
+        $mailChimpTags->setMailChimpHelper($helper);
+        $mailChimpTags->setStoreId($storeId);
+        $mailChimpTags->setSubscriber($subscriber);
+        $mailChimpTags->setCustomer(
+            $this->getCustomerByWebsiteAndId()
+            ->setWebsiteId($this->getWebSiteByStoreId($storeId))->load($subscriber->getCustomerId())
+        );
+        $mailChimpTags->buildMailChimpTags();
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: Extract to function the entire 'mailchimp/api_subscribers_mailchimpTags' build.

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 35]
```diff
@@ -381,7 +200,19 @@ public function updateSubscriber($subscriber, $updateStatus = false)
...
+            $mailChimpTags = Mage::getModel('mailchimp/api_subscribers_MailchimpTags');
+            $mailChimpTags->setMailChimpHelper($helper);
+            $mailChimpTags->setStoreId($storeId);
+            $mailChimpTags->setSubscriber($subscriber);
+            $mailChimpTags->setCustomer(
+                $this->getCustomerByWebsiteAndId()->
+                setWebsiteId($this->getWebSiteByStoreId($storeId))->load($subscriber->getCustomerId())
+            );
+
+            $mailChimpTags->buildMailChimpTags();
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: Use same function extracted previously.

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 36]
```diff
@@ -405,13 +236,17 @@ public function updateSubscriber($subscriber, $updateStatus = false)
                 $subscriber->setData("mailchimp_sync_modified", 0);
                 $saveSubscriber = true;
             } catch (MailChimp_Error $e) {
-                if ($newStatus === 'subscribed' && $subscriber->getIsStatusChanged() && !$helper->isSubscriptionConfirmationEnabled($storeId)) {
+                if ($newStatus === 'subscribed' && $subscriber->getIsStatusChanged()
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: Use constant to validate "subscrbied" status.
Also extract condition to function "isSubscribed" or similar.

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 37]
```diff
@@ -405,13 +236,17 @@ public function updateSubscriber($subscriber, $updateStatus = false)
...
+                    && !$helper->isSubscriptionConfirmationEnabled($storeId)) {
                     if (strstr($e->getMailchimpDetails(), 'is in a compliance state')) {
                         try {
-                            $api->lists->members->update($listId, $md5HashEmail, null, 'pending', $mergeVars, $interest);
+                            $api->lists->members->update(
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: Use the library functions "$api->getLists()->getMembers->update" in stead of calling attributes directly.

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 38]
```diff
@@ -544,49 +383,66 @@ public function update($emailAddress, $storeId)
...
-            if ($address->getCountry()) {
-                $addressData["country"] = Mage::getModel('directory/country')->loadByCode($address->getCountry())->getName();
-            }
-        }
-        return $addressData;
+    /**
+     * @param $storeId
+     * @return Mage_Core_Model_Abstract
+     */
+    protected function getWebSiteByStoreId($storeId)
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: Change function name to getWebsiteByStoreId

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers/MailchimpTags.php [hunk 39]
```diff
@@ -0,0 +1,805 @@
...
+    {
+        $this->_mailChimpTags[$key] = $value;
+    }
+
+    public function getMailChimpTagValue($key)
+    {
+        return $this->_mailChimpTags[$key];
+    }
+
+    public function __construct()
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers/MailchimpTags.php]: Move constructor to the top of the class, after attribute declaration.

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers/MailchimpTags.php [hunk 40]
```diff
@@ -0,0 +1,805 @@
...
+     * @param $customer
+     * @param $attribute
+     * @return mixed
+     */
+    protected function getUnknownMergeField($attributeCode, $customer, $attribute)
+    {
+        $optionValue = null;
+
+        $attrValue = $this->getCustomerGroupLabel($attributeCode, $customer);
+        if ($attrValue!== null) {
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers/MailchimpTags.php]: Add blank space after $attrValue

File: app/code/community/Ebizmarts/MailChimp/Model/Observer.php [hunk 41]
```diff
@@ -1117,4 +1120,20 @@ protected function getCatalogProductStatusModel()
     {
         return Mage::getModel('catalog/product_status');
     }
+
+    public function mergeFieldSendBefore(Varien_Event_Observer $observer)
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Observer.php]: Remove unused function.

File: app/code/community/Ebizmarts/MailChimp/Model/Observer.php [hunk 42]
```diff
@@ -1117,4 +1120,20 @@ protected function getCatalogProductStatusModel()
...
+    {
+        if ($observer->getEvent()->getData()['merge_field_tag'] == 'lastname')
+        {
+          //  $observer->getEvent()->setMergeFieldValue('customValue');
+        }
+    }
+
+    public function mergeFieldSendAfter(Varien_Event_Observer $observer)
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Observer.php]: Remove unused function.

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers/MailchimpTags.php [hunk 43]
```diff
@@ -0,0 +1,813 @@
...
+    protected function getNewVarienObject()
+    {
+        return new Varien_Object;
+    }
+    /**
+     * @param $subscriberEmail
+     * @return mixed
+     * @throws Mage_Core_Exception
+     */
+    protected function saveLastOrderInSession()
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers/MailchimpTags.php]: Remove unnecessary function and call directly getLastOrderByEmail when it is required.

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers/MailchimpTags.php [hunk 44]
```diff
@@ -0,0 +1,813 @@
...
+    }
+
+    /**
+     * @param $customAtt
+     * @param $customer
+     * @return array | returns an array with the address if it exists
+     */
+    protected function getAddressForCustomizedAttributes($customAtt, $customer)
+    {
+        $lastOrder = $this->getSubscriberLastOrder();
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers/MailchimpTags.php]: Call to function getLastOrderByEmail to avoid using session.
