### PR TITLE
#793 Add option to send subscription emails via Magento

### LINKED ISSUE #793: Send subscription confirmation email via Magento
### Preconditions
1. Install any version of Magento and M4M1.

### Steps to reproduce
1. Enable confirmation email on subscriptions.
2. Subscribe while NOT being logged in.

### Expected result
1. Be allowed to choose between MailChimp or Magento to send confirmation email.

### Actual result
1. Email is always sent via MailChimp.

### PR DESCRIPTION
**Pull request by ebizmarts-keller**
- Add setting to the backend to choose between Magento email or Mailchimp email

### CODE REVIEW

File: app/code/community/Ebizmarts/MailChimp/Model/Subscriber.php [hunk 1]
```diff
@@ -30,10 +30,70 @@ public function sendConfirmationRequestEmail()
 
     public function sendConfirmationSuccessEmail()
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Subscriber.php]: At this point the subscription to MailChimp should be sent and not before in order to avoid incoherence with Magento status.

**Comment by underthecocotree** [comment]
@Santiagoebizmarts, I had a look at the latest version and master and I don't see these commit being merged.  Is there a plan to merge this to master or to the next version?  

Is it safe to use the develop branch on a production site?
Thanks

**Comment by Santiagoebizmarts** [comment]
Hello @underthecocotree 
If you go to the [issue](https://github.com/mailchimp/mc-magento/issues/793) you can see it is flagged for version 1.1.5

Kind Regards.

**Comment by underthecocotree** [comment]
Oh, my bad. .I saw you had moved it through the milestones.  Missed it on 1.1.5 because it was closed.  

Thanks for that, do you know when 1.1.5 will be released?  I don't see a due date on the milestone.

**Comment by Santiagoebizmarts** [comment]
We did change that milestone because some branding changes were required in the extension.
Version 1.1.15 should be out first week of March.

Kind Regards.
