### PR TITLE
Orders doesnt sync with mailchimp when the order have a child product

### LINKED ISSUE #930: Orders doesn't sync with Mailchimp when the order have a child product
### Preconditions
1. Mailchimp for Magento development version, it doesn't happens in any released version.
2. Magento any version.

### Steps to reproduce
1. Place an order with a child product.
orderWithChildProduct
childProductWithParent

### Expected result
1. The order should sync without any problem

### Actual result
1. The order doesn't sync with Mailchimp throwing the next error:

> Bad Request : A product with the provided variant ID does not exist in the account for this list.

### PR DESCRIPTION
**Pull request by luciaebizmarts**
- Changed how get the child's product collection
- Adapted test to the changes 
- closes #930

### CODE REVIEW

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php [hunk 1]
```diff
@@ -640,12 +596,34 @@ protected function getConfigurableChildrenIds($product)
...
 
     /**
+     * @param $product
      * @param $magentoStoreId
-     * @return Mage_Catalog_Model_Resource_Product_Collection
+     * @param bool $isBuildUpdateProductRequest
+     * @return array | return an array with the childs of the product passed by parameter
      */
-    protected function makeProductChildrenCollection($magentoStoreId)
+    public function makeProductChildrenCollection($product, $magentoStoreId, $isBuildUpdateProductRequest = false)
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php]: Function is not returning a collection as the title suggest. Please change title to match what is returned.
