### PR TITLE
Fix api null issue613

### LINKED ISSUE #613: Altering email address of customer results in "Call to member function on null" when no API key is configured
Preconditions:
1. Have Magento 1 (any version) installed
2. mc-magento 1.1.10
3. Do not configure API-KEY for MailChimp

Steps to reproduce:
1. Edit a customer
2. Change her email address
3. Save customer

Expected result:
Customer is saved and her email address is as specifed

Actual result:
HTTP status code 500 occurs. In server log you find the following:
```
PHP Fatal error:  Call to a member function update() on null in /var/www/html/app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php on line 472"
```

The reason is that in `Ebizmarts_MailChimp_Helper_Data::getApi()` the class `Ebizmarts_MailChimp` is only instantiated if an API-Key is configured for the specified scope, otherwise `null` is returned.
In line 472 of class `Ebizmarts_MailChimp_Model_Api_Subscribers` no check is ever made whether `Ebizmarts_MailChimp_Helper_Data::getApi()` returned an instance or `null`, it always presumes that an instance was returned.

### PR DESCRIPTION
**Pull request by Santiagoebizmarts**
closes #613

### CODE REVIEW

File: app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/System/Config/ResetErrors.php [hunk 1]
```diff
@@ -27,7 +27,7 @@ protected function _getElementHtml(Varien_Data_Form_Element_Abstract $element)
     public function getButtonHtml()
     {
         $scopeArray = explode('-', Mage::helper('mailchimp')->getScopeString());
-        if (Mage::helper('mailchimp')->isMailChimpEnabled($scopeArray[1], $scopeArray[0]) || $scopeArray[1] == 0) {
+        if (Mage::helper('mailchimp')->isSubscriptionEnabled($scopeArray[1], $scopeArray[0]) || $scopeArray[1] == 0) {
```
Comment (bcerban) [inline app/code/community/Ebizmarts/MailChimp/Block/Adminhtml/System/Config/ResetErrors.php]: magical indexes

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Customers.php [hunk 2]
```diff
@@ -206,11 +203,11 @@ protected function getOptinConfiguration($magentoStoreId)
...
      * @param $mailchimpStoreId
-     * @param null             $syncDelta
-     * @param null             $syncError
-     * @param int              $syncModified
-     * @param null             $syncedFlag
-     * @param bool             $saveOnlyIfexists
+     * @param null $syncDelta
+     * @param null $syncError
+     * @param int $syncModified
+     * @param null $syncedFlag
```
Comment (bcerban) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Customers.php]: fix `null` var types

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php [hunk 3]
```diff
@@ -246,7 +246,12 @@ protected function GeneratePOSTPayload($order, $mailchimpStoreId, $magentoStoreI
         }
 
         //customer data
-        $api = $helper->getApi($magentoStoreId);
+        try {
+            $api = $helper->getApi($magentoStoreId);
+        } catch (Exception $e) {
```
Comment (bcerban) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php]: Change `Exception` to `Ebizmarts_MailChimp_Helper_Data_ApiKeyException`

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php [hunk 4]
```diff
@@ -269,28 +269,10 @@ protected function _buildProductData($product, $magentoStoreId, $isVariant = tru
...
-            $this->_updateIfEnabled($productId, $curStoreId);
-        }
-    }
-
-    /**
-     * Update product sync data if
-     *
-     * @param $productId
-     * @param $storeId
+     * @param $mailchimpStoreId
```
Comment (bcerban) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php]: var types

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Stores.php [hunk 5]
```diff
@@ -25,8 +25,8 @@ class Ebizmarts_MailChimp_Model_Api_Stores
     public function createMailChimpStore($mailChimpStoreId, $listId = null, $scopeId, $scope)
     {
         $helper = $this->makeHelper();
-        $api = $helper->getApi($scopeId, $scope);
-        if ($api) {
+        try {
```
Comment (bcerban) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Stores.php]: Suggestion: move `$listId` checks up, before trying to get the API object. An `Ebizmarts_MailChimp_Helper_Data_ApiKeyException` could hide the more important exception here, that no lists are configured in MC.

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 6]
```diff
@@ -89,7 +87,6 @@ public function createBatchJson($listId, $storeId, $limit)
 
                 $counter++;
             }
```
Comment (bcerban) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: fix indentation

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php [hunk 7]
```diff
@@ -330,53 +327,64 @@ public function updateSubscriber($subscriber, $updateStatus = false)
...
-                        $subscriber->setSubscriberStatus(Mage_Newsletter_Model_Subscriber::STATUS_UNCONFIRMED);
-                        $message = $helper->__('To begin receiving the newsletter, you must first confirm your subscription');
-                        Mage::getSingleton('core/session')->addWarning($message);
-                    } catch (MailChimp_Error $e) {
+        $subscriptionEnabled = $helper->isSubscriptionEnabled($storeId);
+        if ($subscriptionEnabled) {
+            $listId = $helper->getGeneralList($storeId);
+            $newStatus = $this->translateMagentoStatusToMailchimpStatus($subscriber->getStatus(), $storeId);
+            $forceStatus = ($updateStatus) ? $newStatus : null;
+            try {
```
Comment (bcerban) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Subscribers.php]: Move the `try/catch` for `getApi` to a separate block (like in app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php line 249), to avoid nested `try/catch` blocks.

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Carts.php [hunk 8]
```diff
@@ -402,100 +406,105 @@ protected function getBatchLimitFromConfig()
...
-        if ($cart->getCustomerId()) {
-            try {
-                $customer = $api->ecommerce->customers->get($mailchimpStoreId, $cart->getCustomerId(), 'email_address');
-            } catch (MailChimp_Error $e) {
-                $err = $e->getMailchimpTitle();
-                if (!preg_match('/Resource Not Found for Api Call/', $err)) {
-                    $msg = "Failed to lookup e-commerce customer via ID " . $cart->getCustomerId();
-                    $helper->logError($msg . ': ' . $e->getFriendlyMessage(), $magentoStoreId);
+        $customer = array();
+        try {
```
Comment (bcerban) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Carts.php]: Move the `try/catch` for `getApi` to a separate block (like in app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php line 249), to avoid nested `try/catch` blocks.

File: app/code/community/Ebizmarts/MailChimp/Model/Observer.php [hunk 9]
```diff
@@ -126,65 +225,128 @@ public function customerSaveBefore(Varien_Event_Observer $observer)
...
+                if ($subscriber) {
+                    $helper->subscribeMember($subscriber, true);
+                }
+            }
+
+            $this->removeCampaignData();
+
+            $items = $order->getAllItems();
+            foreach ($items as $item) {
+                if ($item->getProductType() == 'bundle' || $item->getProductType() == 'configurable') {
```
Comment (bcerban) [inline app/code/community/Ebizmarts/MailChimp/Model/Observer.php]: use `Mage_Catalog_Model_Product_Type::TYPE_BUNDLE` and `Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE`

File: app/code/community/Ebizmarts/MailChimp/Model/Observer.php [hunk 10]
```diff
@@ -338,88 +524,67 @@ public function loadCustomerToQuote(Varien_Event_Observer $observer)
...
 
-            $mailchimpStoreId = $this->makeHelper()->getMCStoreId($order->getStoreId());
-            $this->makeHelper()->saveEcommerceSyncData($item->getProductId(), Ebizmarts_MailChimp_Model_Config::IS_PRODUCT, $mailchimpStoreId, null, null, 1, null, null, null, true);
-        }
+            $items = $creditMemo->getAllItems();
 
-        return $observer;
-    }
+            foreach ($items as $item) {
+                if ($item->getProductType() == 'bundle' || $item->getProductType() == 'configurable') {
```
Comment (bcerban) [inline app/code/community/Ebizmarts/MailChimp/Model/Observer.php]: use `Mage_Catalog_Model_Product_Type::TYPE_BUNDLE` and `Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE`

File: app/code/community/Ebizmarts/MailChimp/Model/Observer.php [hunk 11]
```diff
@@ -338,88 +524,67 @@ public function loadCustomerToQuote(Varien_Event_Observer $observer)
...
+        $helper = $this->makeHelper();
+        $ecomEnabled = $helper->isEcomSyncDataEnabled($storeId);
+
+        if ($ecomEnabled) {
+
+            $mailchimpStoreId = $helper->getMCStoreId($storeId);
+
+            $items = $creditMemo->getAllItems();
+            foreach ($items as $item) {
+                if ($item->getProductType() == 'bundle' || $item->getProductType() == 'configurable') {
```
Comment (bcerban) [inline app/code/community/Ebizmarts/MailChimp/Model/Observer.php]: use `Mage_Catalog_Model_Product_Type::TYPE_BUNDLE` and `Mage_Catalog_Model_Product_Type::TYPE_CONFIGURABLE`

File: app/code/community/Ebizmarts/MailChimp/controllers/WebhookController.php [hunk 12]
```diff
@@ -39,11 +39,14 @@ public function indexAction()
...
                 $storeIds = $helper->getMagentoStoreIdsByListId($listId);
                 if (count($storeIds)) {
-                    $api = $helper->getApi($storeIds[0]);
-                    $webhooks = $api->lists->webhooks->getAll($listId);
-                    foreach ($webhooks['webhooks'] as $webhook) {
-                        if (strpos($webhook['url'], 'monkey/webhook') !== false) {
-                            $api->lists->webhooks->delete($listId, $webhook['id']);
+                    $storeId = $storeIds[0];
+                    if ($helper->isSubscriptionEnabled($storeId)) {
+                        $api = $helper->getApi($storeId);
```
Comment (bcerban) [inline app/code/community/Ebizmarts/MailChimp/controllers/WebhookController.php]: uncontrolled `Ebizmarts_MailChimp_Helper_Data_ApiKeyException`?

File: app/code/community/Ebizmarts/MailChimp/controllers/Adminhtml/MailchimperrorsController.php [hunk 13]
```diff
@@ -75,4 +87,45 @@ protected function _isAllowed()
...
+     * @return Ebizmarts_MailChimp_Model_Api_Batches
+     */
+    protected function getApiBatches()
+    {
+        return Mage::getModel('mailchimp/api_batches');
+    }
+
+    /**
+     * @param $file
+     * @return mixed
```
Comment (bcerban) [inline app/code/community/Ebizmarts/MailChimp/controllers/Adminhtml/MailchimperrorsController.php]: return var types

File: app/code/community/Ebizmarts/MailChimp/controllers/Adminhtml/MailchimperrorsController.php [hunk 14]
```diff
@@ -75,4 +87,45 @@ protected function _isAllowed()
...
+     */
+    protected function getFileContent($file)
+    {
+        return json_decode(file_get_contents($file));
+    }
+
+    /**
+     * @param $file
```
Comment (bcerban) [inline app/code/community/Ebizmarts/MailChimp/controllers/Adminhtml/MailchimperrorsController.php]: vet type

File: app/code/community/Ebizmarts/MailChimp/controllers/Adminhtml/EcommerceController.php [hunk 15]
```diff
@@ -14,80 +14,85 @@ class Ebizmarts_MailChimp_Adminhtml_EcommerceController extends Mage_Adminhtml_C
...
-            $stores = Mage::app()->getStores();
+            $stores = $mageApp->getStores();
             if ($scopeArray[1] == 0) {
                 foreach ($stores as $store) {
-                    Mage::helper('mailchimp')->resetErrors($store->getId());
+                    $helper->resetErrors($store->getId());
                 }
             }
-            Mage::helper('mailchimp')->resetErrors($scopeArray[1], $scopeArray[0]);
+            $helper->resetErrors($scopeArray[1], $scopeArray[0]);
```
Comment (bcerban) [inline app/code/community/Ebizmarts/MailChimp/controllers/Adminhtml/EcommerceController.php]: magic indexes

File: app/code/community/Ebizmarts/MailChimp/controllers/Adminhtml/EcommerceController.php [hunk 16]
```diff
@@ -14,80 +14,85 @@ class Ebizmarts_MailChimp_Adminhtml_EcommerceController extends Mage_Adminhtml_C
 {
     public function resetLocalErrorsAction()
     {
-        $param = Mage::app()->getRequest()->getParam('scope');
+        $helper = $this->makeHelper();
+        $mageApp = $helper->getMageApp();
+        $param = $mageApp->getRequest()->getParam('scope');
         $scopeArray = explode('-', $param);
         $result = 1;
```
Comment (bcerban) [inline app/code/community/Ebizmarts/MailChimp/controllers/Adminhtml/EcommerceController.php]: magic result number

File: app/code/community/Ebizmarts/MailChimp/Model/System/Config/Source/List.php [hunk 17]
```diff
@@ -20,17 +20,21 @@ class Ebizmarts_MailChimp_Model_System_Config_Source_List
      */
     protected $_lists = null;
 
+    protected $_helper;
```
Comment (bcerban) [inline app/code/community/Ebizmarts/MailChimp/Model/System/Config/Source/List.php]: var type

File: app/code/community/Ebizmarts/MailChimp/Model/System/Config/Source/List.php [hunk 18]
```diff
@@ -20,17 +20,21 @@ class Ebizmarts_MailChimp_Model_System_Config_Source_List
...
      * Load lists and store on class property
      */
     public function __construct()
     {
-        $scopeArray = explode('-', Mage::helper('mailchimp')->getScopeString());
+        $helper = $this->_helper = $this->makeHelper();
+        $scopeArray = explode('-', $helper->getScopeString());
         if ($this->_lists == null) {
-            $apiKey = Mage::helper('mailchimp')->getApiKey($scopeArray[1], $scopeArray[0]);
+            $apiKey = $helper->getApiKey($scopeArray[1], $scopeArray[0]);
```
Comment (bcerban) [inline app/code/community/Ebizmarts/MailChimp/Model/System/Config/Source/List.php]: magic indexes

File: app/code/community/Ebizmarts/MailChimp/Model/System/Config/Source/List.php [hunk 19]
```diff
@@ -20,17 +20,21 @@ class Ebizmarts_MailChimp_Model_System_Config_Source_List
...
             if ($apiKey) {
                 try {
-                    $api = Mage::helper('mailchimp')->getApi($scopeArray[1], $scopeArray[0]);
+                    $api = $helper->getApi($scopeArray[1], $scopeArray[0]);
```
Comment (bcerban) [inline app/code/community/Ebizmarts/MailChimp/Model/System/Config/Source/List.php]: magic indexes

File: app/code/community/Ebizmarts/MailChimp/Model/System/Config/Source/Account.php [hunk 20]
```diff
@@ -39,52 +39,61 @@ class Ebizmarts_MailChimp_Model_System_Config_Source_Account
...
-                        $this->_accountDetails['total_orders'] = $totalOrders['total_items'];
-                        $totalCarts = $api->ecommerce->carts->getAll($mcStoreId, 'total_items');
-                        $this->_accountDetails['total_carts'] = $totalCarts['total_items'];
-                    } catch (MailChimp_Error $e) {
-                        $helper->deleteLocalMCStoreData($mcStoreId, $scopeArray[1], $scopeArray[0]);
-                        if ($listId) {
-                            $helper->createStore($listId, $scopeArray[1], $scopeArray[0]);
-                            $message = $helper->__('Looks like your MailChimp store was deleted. A new one has been created.');
-                            Mage::getSingleton('adminhtml/session')->addWarning($message);
+        try {
```
Comment (bcerban) [inline app/code/community/Ebizmarts/MailChimp/Model/System/Config/Source/Account.php]: Move the `try/catch` for `getApi` to a separate block (like in app/code/community/Ebizmarts/MailChimp/Model/Api/Orders.php line 249), to avoid nested `try/catch` blocks.
