### PR TITLE
Issue 1210 update pcd prl

### LINKED ISSUE #1210: Promo Codes doesn't get sent when updating Promo Rules
Promo Rules won't update in Mailchimp alongside Promo Codes when sending them from Magento to Mailchimp

### Preconditions
1. Magento 1.9.4.5
2. Mailchimp 1.1.21

### Steps to reproduce
1. Update a Promo Rule
2. Wait for it to get sent or Resend Promo Rules in the Resend Ecommerce Data button
3. Check the Mailchimp Promo Codes

### Expected result
1. The Promo Rules should get Updated alongside the Promo Codes.

### Actual result
1. The Promo Rules don't get updated and the Promo Codes seems to get stuck in the mailchimp_ecommerce_sync_data table.

### PR DESCRIPTION
**Pull request by roberto-ebizmarts**
closes #1210

### CODE REVIEW

File: app/code/community/Ebizmarts/MailChimp/Model/Api/PromoCodes.php [hunk 1]
```diff
@@ -196,6 +197,75 @@ protected function _getNewPromoCodes()
...
+    {
+        $mailchimpStoreId = $this->getMailchimpStoreId();
+        $batchArray = array();
+        $counter = 0;
+
+        $modifiedPromoCodes = $this->buildEcommerceCollectionToSync(
+            Ebizmarts_MailChimp_Model_Config::IS_PROMO_CODE,
+            "m4m.mailchimp_sync_modified = 1",
+            "modified"
+        );
```
Comment (gonzaloebiz) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/PromoCodes.php:213]: You must use the mailchimpStoreId in the collection

**Review by gonzaloebiz — APPROVED** [review]
