### PR TITLE
Handle json_encode errors correctly #1010

### LINKED ISSUE #1010: Handle json_encode errors correctly
### Preconditions

1. Mailchimp for Magento 1.1.17

### Steps to reproduce

1. json_encode fails. May happen with non UTF-8 characters.

### Expected result

1. Error is logged.

### Actual result

1. The same "An empty operation was detected" message is logged every time.

### PR DESCRIPTION
**Pull request by brian-ebizmarts**
closes #1010 #1032

### CODE REVIEW

File: app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php [hunk 1]
```diff
@@ -324,6 +388,7 @@ protected function _buildProductData($product, $magentoStoreId, $isVariant = tru
         //data applied for both root and varient products
         $data["id"] = $productId;
         $data["title"] = $rc->getAttributeRawValue($productId, 'name', $magentoStoreId);
+        if($break)  $data["title"] = $rc->getAttributeRawValue($productId, 'name', $magentoStoreId) ."\xB1\x31";
```
Comment (Santiagoebizmarts) [inline app/code/community/Ebizmarts/MailChimp/Model/Api/Products.php]: Please avoid this one line if statements. Standards recommend always using standard format with brackets.
